### ISSUE TITLE
For GP2 or GP21 used as input the pullup is not enabled

### ISSUE THREAD

**Issue by winkleink** [raspberrypilearning/physical-computing-with-scratch#11]
In the example a switch is used without a pull up resistor yet the initialisation of the pin does not enable the internal pull up resistor so the pin is floating as an input which may cause inconsistent results.

Should it be 
config2inpullup

not 

config2in

**Comment by lawsie** [comment]
@MarcScott Over to you

**Comment by MarcScott** [comment]
From the documentation on [Scratch GPIO](https://www.raspberrypi.org/documentation/usage/scratch/gpio/README.md):
```For input pins we can use 'in' or 'input'. Both of these are treated the same as 'inpullup' or 'inputpullup' and default to setting the pull-up resistor to pull up the signal. ```
So it should default to a pullup and prevent a floating pin

**Comment by winkleink** [comment]
Thanks for clarifying.
